run_configs:
  tune: false
  train: true
  use_default: false
  train_tok: false

storage:
  url:  "hyperparameter.db"
  engine: 
      pool_size: 20
      connect_args: {"timeout": 10}

tune_configs:
  direction: minimize
  load_if_exists: true
  study_name: "smalltune"

hyperparameters:
  lr:           # log-uniform search
    type: loguniform
    range: [1e-3, 3e-3]

  dropout:      # uniform float search
    type: uniform
    range: [0.05, 0.2]

  # block_size: # categorical choices
  #   type: categorical
  #   values: [64, 128]
